### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by amartya-rs**
### In this PR:
- Implemented basic routing
- Landing page

### Preview Link: https://deploy-preview-1--dopenotes.netlify.app/

### CODE REVIEW

**Review by iRohitGaur — APPROVED** [review]
UI looks nice. Code is clean and understandable. Good to merge 👍🏻

**Comment by archit7448** [comment]
Nice UI code is clean and proper structure looks good to merge

**Review by srishtigautam21 — APPROVED** [review]
clean code
good to merge

**Review by Shubhamkr2610 — APPROVED** [review]
your code is clean and readable . easy to understand , you are good to go

**Pull request merged**
